// 🔥 GENERATED FILE: DO NOT EDIT 🔥
//
// This file is generated by lib/scripts/utils/gen_env_config.sh
// It contains all environment-specific variables for the app.
// Generated for workflow: ios-workflow

class EnvConfig {
  // App Metadata
  static const String appId = "1003";
  static const String versionName = "1.0.1";
  static const int versionCode = 1;
  static const String appName = "Twinklub App";
  static const String orgName = "JPR Garments";
  static const String webUrl = "https://twinklub.com/";
  static const String userName = "prasannasrie";
  static const String emailId = "prasannasrinivasan32@gmail.com";
  static const String branch = "main";
  static const String workflowId = "ios-workflow";

  // Package Identifiers
  static const String pkgName = "";
  static const String bundleId = "com.twinklub.twinklub";

  // Feature Flags (converted to bool)
  static const bool pushNotify = true;
  static const bool isChatbot = true;
  static const bool isDomainUrl = true;
  static const bool isSplash = true;
  static const bool isPulldown = true;
  static const bool isBottommenu = true;
  static const bool isLoadIndicator = true;

  // Permissions (converted to bool)
  static const bool isCamera = false;
  static const bool isLocation = false;
  static const bool isMic = true;
  static const bool isNotification = true;
  static const bool isContact = false;
  static const bool isBiometric = false;
  static const bool isCalendar = false;
  static const bool isStorage = true;

  // UI/Branding
  static const String logoUrl =
      "https://raw.githubusercontent.com/prasanna91/QuikApp/main/twinklub_png_logo.png";
  static const String splashUrl =
      "https://raw.githubusercontent.com/prasanna91/QuikApp/main/twinklub_png_logo.png";
  static const String splashBg = "";
  static const String splashBgColor = "#cbdbf5";
  static const String splashTagline = "TWINKLUB";
  static const String splashTaglineColor = "#a30237";
  static const String splashAnimation = "zoom";
  static const int splashDuration = 4;

  // Bottom Menu Configuration
  static const String bottommenuItems =
      """[{"label":"Home","icon":{"type":"preset","name":"home_outlined"},"url":"https://twinklub.com/"},{"label":"New Arraivals","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/card.svg","icon_size":"24"},"url":"https://www.twinklub.com/collections/new-arrivals"},{"label":"Collections","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/about.svg","icon_size":"24"},"url":"https://www.twinklub.com/collections/all"},{"label":"Contact","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/contact.svg","icon_size":"24"},"url":"https://www.twinklub.com/account"}]""";
  static const String bottommenuBgColor = "#FFFFFF";
  static const String bottommenuIconColor = "#6d6e8c";
  static const String bottommenuTextColor = "#6d6e8c";
  static const String bottommenuFont = "DM Sans";
  static const double bottommenuFontSize = 12;
  static const bool bottommenuFontBold = false;
  static const bool bottommenuFontItalic = false;
  static const String bottommenuActiveTabColor = "#a30237";
  static const String bottommenuIconPosition = "above";

  // Firebase Configuration
  static const String firebaseConfigAndroid = "";
  static const String firebaseConfigIos =
      "https://raw.githubusercontent.com/prasanna91/QuikApp/main/GoogleService-Info-TK.plist";

  // Android Signing
  static const String keyStoreUrl = "";
  static const String cmKeystorePassword = "";
  static const String cmKeyAlias = "";
  static const String cmKeyPassword = "";

  // iOS Signing
  static const String appleTeamId = "";
  static const String apnsKeyId = "V566SWNF69";
  static const String apnsAuthKeyUrl =
      "https://raw.githubusercontent.com/prasanna91/QuikApp/main/AuthKey_V566SWNF69.p8";
  static const String certPassword = "qwerty123";
  static const String profileUrl =
      "https://raw.githubusercontent.com/prasanna91/QuikApp/main/Twinklub_AppStore.mobileprovision";
  static const String certP12Url =
      "https://raw.githubusercontent.com/prasanna91/QuikApp/main/Certificates.p12";
  static const String certCerUrl =
      "https://raw.githubusercontent.com/prasanna91/QuikApp/main/ios_distribution17-07.cer";
  static const String certKeyUrl =
      "https://raw.githubusercontent.com/prasanna91/QuikApp/main/private.key";
  static const String profileType = "app-store";
  static const String appStoreConnectKeyIdentifier = "S95LCWAH99";

  // Build Environment
  static const String buildId = "unknown";
  static const String buildDir = "";
  static const String projectRoot = "";
  static const String outputDir = "output/ios";

  // Utility Methods
  static bool get isAndroidBuild => workflowId.startsWith('android');
  static bool get isIosBuild => workflowId.contains('ios');
  static bool get isCombinedBuild => workflowId == 'combined';
  static bool get hasFirebase =>
      firebaseConfigAndroid.isNotEmpty || firebaseConfigIos.isNotEmpty;
  static bool get hasKeystore => keyStoreUrl.isNotEmpty;
  static bool get hasIosSigning =>
      certPassword.isNotEmpty && profileUrl.isNotEmpty;
}
