#!/bin/bash
set -euo pipefail

# Logging functions
log() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ENV_CONFIG] $1"; }
log_info() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ENV_CONFIG] 🔍 $1"; }
log_success() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ENV_CONFIG] ✅ $1"; }
log_error() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ENV_CONFIG] ❌ $1"; }

log "🚀 Generating Environment Configuration Files"

# Create lib/config directory
mkdir -p lib/config

# Generate env_config.dart
log_info "Generating env_config.dart"
cat > lib/config/env_config.dart << EOF
// Generated by gen_env_config.sh
// Do not edit manually

class EnvConfig {
  // App Information
  static const String appName = "$APP_NAME";
  static const String bundleId = "$BUNDLE_ID";
  static const String versionName = "$VERSION_NAME";
  static const String versionCode = "$VERSION_CODE";
  static const String appId = "$APP_ID";
  static const String orgName = "$ORG_NAME";
  static const String webUrl = "$WEB_URL";
  static const String pkgName = "$PKG_NAME";
  
  // User Information
  static const String userName = "$USER_NAME";
  static const String emailId = "$EMAIL_ID";
  
  // Feature Flags
  static const bool pushNotify = $PUSH_NOTIFY;
  static const bool isChatbot = $IS_CHATBOT;
  static const bool isDomainUrl = $IS_DOMAIN_URL;
  static const bool isSplash = $IS_SPLASH;
  static const bool isPulldown = $IS_PULLDOWN;
  static const bool isBottomMenu = $IS_BOTTOMMENU;
  static const bool isLoadInd = $IS_LOAD_IND;
  
  // Permissions
  static const bool isCamera = $IS_CAMERA;
  static const bool isLocation = $IS_LOCATION;
  static const bool isMic = $IS_MIC;
  static const bool isNotification = $IS_NOTIFICATION;
  static const bool isContact = $IS_CONTACT;
  static const bool isBiometric = $IS_BIOMETRIC;
  static const bool isCalendar = $IS_CALENDAR;
  static const bool isStorage = $IS_STORAGE;
  
  // UI Configuration
  static const String logoUrl = "$LOGO_URL";
  static const String splashUrl = "$SPLASH_URL";
  static const String splashBgColor = "$SPLASH_BG_COLOR";
  static const String splashTagline = "$SPLASH_TAGLINE";
  static const String splashTaglineColor = "$SPLASH_TAGLINE_COLOR";
  static const String splashBgUrl = "$SPLASH_BG_URL";
  static const String splashAnimation = "$SPLASH_ANIMATION";
  static const String splashDuration = "$SPLASH_DURATION";
  
  // Bottom Menu Configuration
  static const String bottomMenuItems = "$BOTTOMMENU_ITEMS";
  static const String bottomMenuBgColor = "$BOTTOMMENU_BG_COLOR";
  static const String bottomMenuIconColor = "$BOTTOMMENU_ICON_COLOR";
  static const String bottomMenuTextColor = "$BOTTOMMENU_TEXT_COLOR";
  static const String bottomMenuFont = "$BOTTOMMENU_FONT";
  static const String bottomMenuFontSize = "$BOTTOMMENU_FONT_SIZE";
  static const String bottomMenuFontBold = "$BOTTOMMENU_FONT_BOLD";
  static const String bottomMenuFontItalic = "$BOTTOMMENU_FONT_ITALIC";
  static const String bottomMenuActiveTabColor = "$BOTTOMMENU_ACTIVE_TAB_COLOR";
  static const String bottomMenuIconPosition = "$BOTTOMMENU_ICON_POSITION";
  
  // Firebase Configuration
  static const String firebaseConfigIos = "$FIREBASE_CONFIG_IOS";
  static const String firebaseConfigAndroid = "$FIREBASE_CONFIG_ANDROID";
  
  // iOS Signing
  static const String appleTeamId = "$APPLE_TEAM_ID";
  static const String profileType = "$PROFILE_TYPE";
  static const String isTestflight = "$IS_TESTFLIGHT";
  
  // Email Configuration
  static const bool enableEmailNotifications = $ENABLE_EMAIL_NOTIFICATIONS;
  static const String emailSmtpServer = "$EMAIL_SMTP_SERVER";
  static const String emailSmtpPort = "$EMAIL_SMTP_PORT";
  static const String emailSmtpUser = "$EMAIL_SMTP_USER";
  static const String emailSmtpPass = "$EMAIL_SMTP_PASS";
  
  // APNS Configuration
  static const String apnsKeyId = "$APNS_KEY_ID";
  static const String apnsAuthKeyUrl = "$APNS_AUTH_KEY_URL";
  
  // Android Keystore
  static const String keyStoreUrl = "$KEY_STORE_URL";
  static const String cmKeystorePassword = "$CM_KEYSTORE_PASSWORD";
  static const String cmKeyAlias = "$CM_KEY_ALIAS";
  static const String cmKeyPassword = "$CM_KEY_PASSWORD";
  
  // App Store Connect
  static const String appStoreConnectKeyIdentifier = "$APP_STORE_CONNECT_KEY_IDENTIFIER";
  static const String appStoreConnectIssuerId = "$APP_STORE_CONNECT_ISSUER_ID";
  static const String appStoreConnectApiKeyUrl = "$APP_STORE_CONNECT_API_KEY_URL";
  
  // Workflow
  static const String workflowId = "$WORKFLOW_ID";
}
EOF

log_success "✅ Generated env_config.dart"

# Generate exportOptions.plist for iOS
log_info "Generating exportOptions.plist"
cat > scripts/exportOptions.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>$PROFILE_TYPE</string>
    <key>provisioningProfiles</key>
    <dict>
        <key>$BUNDLE_ID</key>
        <string>$APP_NAME</string>
    </dict>
    <key>teamID</key>
    <string>$APPLE_TEAM_ID</string>
    <key>uploadBitcode</key>
    <false/>
    <key>uploadSymbols</key>
    <true/>
    <key>signingStyle</key>
    <string>automatic</string>
    <key>stripSwiftSymbols</key>
    <true/>
    <key>compileBitcode</key>
    <false/>
</dict>
</plist>
EOF

log_success "✅ Generated exportOptions.plist"

# Generate environment.g.dart for Flutter
log_info "Generating environment.g.dart"
cat > lib/config/environment.g.dart << EOF
// Generated by gen_env_config.sh
// Do not edit manually

class Environment {
  static const String appName = "$APP_NAME";
  static const String bundleId = "$BUNDLE_ID";
  static const String versionName = "$VERSION_NAME";
  static const String versionCode = "$VERSION_CODE";
  static const String appId = "$APP_ID";
  static const String orgName = "$ORG_NAME";
  static const String webUrl = "$WEB_URL";
  static const String pkgName = "$PKG_NAME";
  static const String userName = "$USER_NAME";
  static const String emailId = "$EMAIL_ID";
  static const String workflowId = "$WORKFLOW_ID";
}
EOF

log_success "✅ Generated environment.g.dart"

# Generate .env file for local development
log_info "Generating .env file"
cat > .env << EOF
# App Configuration
APP_NAME=$APP_NAME
BUNDLE_ID=$BUNDLE_ID
VERSION_NAME=$VERSION_NAME
VERSION_CODE=$VERSION_CODE
APP_ID=$APP_ID
ORG_NAME=$ORG_NAME
WEB_URL=$WEB_URL
PKG_NAME=$PKG_NAME

# User Configuration
USER_NAME=$USER_NAME
EMAIL_ID=$EMAIL_ID

# Feature Flags
PUSH_NOTIFY=$PUSH_NOTIFY
IS_CHATBOT=$IS_CHATBOT
IS_DOMAIN_URL=$IS_DOMAIN_URL
IS_SPLASH=$IS_SPLASH
IS_PULLDOWN=$IS_PULLDOWN
IS_BOTTOMMENU=$IS_BOTTOMMENU
IS_LOAD_IND=$IS_LOAD_IND

# Permissions
IS_CAMERA=$IS_CAMERA
IS_LOCATION=$IS_LOCATION
IS_MIC=$IS_MIC
IS_NOTIFICATION=$IS_NOTIFICATION
IS_CONTACT=$IS_CONTACT
IS_BIOMETRIC=$IS_BIOMETRIC
IS_CALENDAR=$IS_CALENDAR
IS_STORAGE=$IS_STORAGE

# UI Configuration
LOGO_URL=$LOGO_URL
SPLASH_URL=$SPLASH_URL
SPLASH_BG_COLOR=$SPLASH_BG_COLOR
SPLASH_TAGLINE=$SPLASH_TAGLINE
SPLASH_TAGLINE_COLOR=$SPLASH_TAGLINE_COLOR
SPLASH_BG_URL=$SPLASH_BG_URL
SPLASH_ANIMATION=$SPLASH_ANIMATION
SPLASH_DURATION=$SPLASH_DURATION

# Bottom Menu Configuration
BOTTOMMENU_ITEMS=$BOTTOMMENU_ITEMS
BOTTOMMENU_BG_COLOR=$BOTTOMMENU_BG_COLOR
BOTTOMMENU_ICON_COLOR=$BOTTOMMENU_ICON_COLOR
BOTTOMMENU_TEXT_COLOR=$BOTTOMMENU_TEXT_COLOR
BOTTOMMENU_FONT=$BOTTOMMENU_FONT
BOTTOMMENU_FONT_SIZE=$BOTTOMMENU_FONT_SIZE
BOTTOMMENU_FONT_BOLD=$BOTTOMMENU_FONT_BOLD
BOTTOMMENU_FONT_ITALIC=$BOTTOMMENU_FONT_ITALIC
BOTTOMMENU_ACTIVE_TAB_COLOR=$BOTTOMMENU_ACTIVE_TAB_COLOR
BOTTOMMENU_ICON_POSITION=$BOTTOMMENU_ICON_POSITION

# Firebase Configuration
FIREBASE_CONFIG_IOS=$FIREBASE_CONFIG_IOS
FIREBASE_CONFIG_ANDROID=$FIREBASE_CONFIG_ANDROID

# iOS Signing
APPLE_TEAM_ID=$APPLE_TEAM_ID
PROFILE_TYPE=$PROFILE_TYPE
IS_TESTFLIGHT=$IS_TESTFLIGHT

# Email Configuration
ENABLE_EMAIL_NOTIFICATIONS=$ENABLE_EMAIL_NOTIFICATIONS
EMAIL_SMTP_SERVER=$EMAIL_SMTP_SERVER
EMAIL_SMTP_PORT=$EMAIL_SMTP_PORT
EMAIL_SMTP_USER=$EMAIL_SMTP_USER
EMAIL_SMTP_PASS=$EMAIL_SMTP_PASS

# APNS Configuration
APNS_KEY_ID=$APNS_KEY_ID
APNS_AUTH_KEY_URL=$APNS_AUTH_KEY_URL

# Android Keystore
KEY_STORE_URL=$KEY_STORE_URL
CM_KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD
CM_KEY_ALIAS=$CM_KEY_ALIAS
CM_KEY_PASSWORD=$CM_KEY_PASSWORD

# App Store Connect
APP_STORE_CONNECT_KEY_IDENTIFIER=$APP_STORE_CONNECT_KEY_IDENTIFIER
APP_STORE_CONNECT_ISSUER_ID=$APP_STORE_CONNECT_ISSUER_ID
APP_STORE_CONNECT_API_KEY_URL=$APP_STORE_CONNECT_API_KEY_URL

# Workflow
WORKFLOW_ID=$WORKFLOW_ID
EOF

log_success "✅ Generated .env file"

log_success "✅ Environment configuration generation completed successfully"
exit 0 