#!/bin/bash
set -e

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ENV_GEN] $1"
}

generate_env_config() {
  log "🚀 Starting environment configuration generation..."

  WORKFLOW_ID="${WORKFLOW_ID:-unknown}"
  log "Detected workflow: $WORKFLOW_ID"

  IS_ANDROID_WORKFLOW=false
  IS_IOS_WORKFLOW=false

  case "$WORKFLOW_ID" in
    android-free|android-paid|android-publish)
      IS_ANDROID_WORKFLOW=true
      ;;
    ios-workflow|ios-akash)
      IS_IOS_WORKFLOW=true
      ;;
    combined)
      IS_ANDROID_WORKFLOW=true
      IS_IOS_WORKFLOW=true
      ;;
    *)
      IS_ANDROID_WORKFLOW=true
      IS_IOS_WORKFLOW=true
      ;;
  esac

  mkdir -p lib/config || log "Warning: Failed to create lib/config"

  # For multi-line Dart constants, use literal newlines (here-doc style)
  if [ "$IS_ANDROID_WORKFLOW" = true ]; then
    ANDROID_PKG="  static const String pkgName = \"${PKG_NAME:-}\";"
    ANDROID_FIREBASE="  static const String firebaseConfigAndroid = \"${FIREBASE_CONFIG_ANDROID:-}\";"
    ANDROID_SIGNING=$'  static const String keyStoreUrl = "'${KEY_STORE_URL:-}'";\n  static const String cmKeystorePassword = "'${CM_KEYSTORE_PASSWORD:-}'";\n  static const String cmKeyAlias = "'${CM_KEY_ALIAS:-}'";\n  static const String cmKeyPassword = "'${CM_KEY_PASSWORD:-}'";'
  else
    ANDROID_PKG="  static const String pkgName = \"\";"
    ANDROID_FIREBASE="  static const String firebaseConfigAndroid = \"\";"
    ANDROID_SIGNING=$'  static const String keyStoreUrl = "";\n  static const String cmKeystorePassword = "";\n  static const String cmKeyAlias = "";\n  static const String cmKeyPassword = "";'
  fi

  # iOS config
  if [ "$IS_IOS_WORKFLOW" = true ]; then
    IOS_PKG="  static const String bundleId = \"${BUNDLE_ID:-}\";"
    IOS_FIREBASE="  static const String firebaseConfigIos = \"${FIREBASE_CONFIG_IOS:-}\";"
    read -r -d '' IOS_SIGNING << EOM || true
  static const String appleTeamId = "${APPLE_TEAM_ID:-}";
  static const String apnsKeyId = "${APNS_KEY_ID:-}";
  static const String apnsAuthKeyUrl = "${APNS_AUTH_KEY_URL:-}";
  static const String certPassword = "${CERT_PASSWORD:-}";
  static const String profileUrl = "${PROFILE_URL:-}";
  static const String certP12Url = "${CERT_P12_URL:-}";
  static const String certCerUrl = "${CERT_CER_URL:-}";
  static const String certKeyUrl = "${CERT_KEY_URL:-}";
  static const String profileType = "${PROFILE_TYPE:-app-store}";
  static const String appStoreConnectKeyIdentifier = "${APP_STORE_CONNECT_KEY_IDENTIFIER:-}";
EOM
  else
    IOS_PKG="  static const String bundleId = \"\";"
    IOS_FIREBASE="  static const String firebaseConfigIos = \"\";"
    read -r -d '' IOS_SIGNING << EOM || true
  static const String appleTeamId = "";
  static const String apnsKeyId = "";
  static const String apnsAuthKeyUrl = "";
  static const String certPassword = "";
  static const String profileUrl = "";
  static const String certP12Url = "";
  static const String certCerUrl = "";
  static const String certKeyUrl = "";
  static const String profileType = "app-store";
  static const String appStoreConnectKeyIdentifier = "";
EOM
  fi

  log "Writing lib/config/env_config.dart..."

  cat > lib/config/env_config.dart <<EOF
// GENERATED FILE: DO NOT EDIT
//
// Generated by lib/scripts/utils/gen_env_config.sh for workflow: $WORKFLOW_ID

class EnvConfig {
  static const String appId = "${APP_ID:-}";
  static const String versionName = "${VERSION_NAME:-1.0.0}";
  static const int versionCode = ${VERSION_CODE:-1};
  static const String appName = "${APP_NAME:-QuikApp}";
  static const String orgName = "${ORG_NAME:-}";
  static const String webUrl = "${WEB_URL:-}";
  static const String userName = "${USER_NAME:-}";
  static const String emailId = "${EMAIL_ID:-}";
  static const String branch = "main";
  static const String workflowId = "$WORKFLOW_ID";

  // Package identifiers
$ANDROID_PKG
$IOS_PKG

  // Feature flags (bool)
  static const bool pushNotify = ${PUSH_NOTIFY:-false};
  static const bool isChatbot = ${IS_CHATBOT:-false};
  static const bool isDomainUrl = ${IS_DOMAIN_URL:-false};
  static const bool isSplash = ${IS_SPLASH:-true};
  static const bool isPulldown = ${IS_PULLDOWN:-true};
  static const bool isBottommenu = ${IS_BOTTOMMENU:-true};
  static const bool isLoadIndicator = ${IS_LOAD_IND:-true};

  // Permissions (bool)
  static const bool isCamera = ${IS_CAMERA:-false};
  static const bool isLocation = ${IS_LOCATION:-false};
  static const bool isMic = ${IS_MIC:-false};
  static const bool isNotification = ${IS_NOTIFICATION:-false};
  static const bool isContact = ${IS_CONTACT:-false};
  static const bool isBiometric = ${IS_BIOMETRIC:-false};
  static const bool isCalendar = ${IS_CALENDAR:-false};
  static const bool isStorage = ${IS_STORAGE:-false};

  // UI / Branding
  static const String logoUrl = "${LOGO_URL:-}";
  static const String splashUrl = "${SPLASH_URL:-}";
  static const String splashBg = "${SPLASH_BG_URL:-}";
  static const String splashBgColor = "${SPLASH_BG_COLOR:-#FFFFFF}";
  static const String splashTagline = "${SPLASH_TAGLINE:-}";
  static const String splashTaglineColor = "${SPLASH_TAGLINE_COLOR:-#000000}";
  static const String splashAnimation = "${SPLASH_ANIMATION:-none}";
  static const int splashDuration = ${SPLASH_DURATION:-3};

  // Bottom Menu Config
  static const String bottommenuItems = """${BOTTOMMENU_ITEMS:-[]}""";
  static const String bottommenuBgColor = "${BOTTOMMENU_BG_COLOR:-#FFFFFF}";
  static const String bottommenuIconColor = "${BOTTOMMENU_ICON_COLOR:-#000000}";
  static const String bottommenuTextColor = "${BOTTOMMENU_TEXT_COLOR:-#000000}";
  static const String bottommenuFont = "${BOTTOMMENU_FONT:-DM Sans}";
  static const double bottommenuFontSize = ${BOTTOMMENU_FONT_SIZE:-14.0};
  static const bool bottommenuFontBold = ${BOTTOMMENU_FONT_BOLD:-false};
  static const bool bottommenuFontItalic = ${BOTTOMMENU_FONT_ITALIC:-false};
  static const String bottommenuActiveTabColor = "${BOTTOMMENU_ACTIVE_TAB_COLOR:-#0000FF}";
  static const String bottommenuIconPosition = "${BOTTOMMENU_ICON_POSITION:-top}";
  static const String bottommenuVisibleOn = "${BOTTOMMENU_VISIBLE_ON:-}";

  // Firebase Config
$ANDROID_FIREBASE
$IOS_FIREBASE

  // Android Signing
$ANDROID_SIGNING

  // iOS Signing
$IOS_SIGNING

  // Build info
  static const String buildId = "${CM_BUILD_ID:-unknown}";
  static const String buildDir = "${CM_BUILD_DIR:-}";
  static const String projectRoot = "${PROJECT_ROOT:-}";
  static const String outputDir = "${OUTPUT_DIR:-output}";

  // Utility getters
  static bool get isAndroidBuild => workflowId.startsWith('android');
  static bool get isIosBuild => workflowId.contains('ios');
  static bool get isCombinedBuild => workflowId == 'combined';
  static bool get hasFirebase => firebaseConfigAndroid.isNotEmpty || firebaseConfigIos.isNotEmpty;
  static bool get hasKeystore => keyStoreUrl.isNotEmpty;
  static bool get hasIosSigning => certPassword.isNotEmpty && profileUrl.isNotEmpty;
}
EOF

  log "✅ env_config.dart generated successfully."

  if [ "${VERBOSE:-false}" = "true" ]; then
    log "Preview of generated config (first 20 lines):"
    head -20 lib/config/env_config.dart | while read -r line; do
      log "  $line"
    done
  fi

  # Simple verification
  if [ "$IS_ANDROID_WORKFLOW" = true ]; then
    if grep -q "static const String pkgName = \"${PKG_NAME:-}\";" lib/config/env_config.dart; then
      log "✅ Android package name set."
    else
      log "⚠️ Android package name missing or incorrect."
    fi
  fi

  if [ "$IS_IOS_WORKFLOW" = true ]; then
    if grep -q "static const String bundleId = \"${BUNDLE_ID:-}\";" lib/config/env_config.dart; then
      log "✅ iOS bundleId set."
    else
      log "⚠️ iOS bundleId missing or incorrect."
    fi
  fi

  return 0
}

generate_env_config
